name: github_issue_app
description: "GitHub issue viewer app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  ferry: ^0.15.0
  ferry_flutter: ^0.9.0
  flutter:
    sdk: flutter
  gql: ^1.0.1-alpha+1730759315362
  gql_http_link: ^1.1.0
  graphql: ^5.2.0-beta.10
  graphql_flutter: ^5.2.0-beta.0
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.4.0
  ferry_generator: ^0.9.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  gql_cache_lens:
    path: ..
  graphql_codegen: ^1.1.0
  pedantic_mono: any

flutter:
  uses-material-design: true
