name: gql_cache_lens
description: "A Flutter DevTools Extension for inspecting GraphQL cache in your Flutter applications."
repository: "https://github.com/temoki/gql_cache_lens"

version: 0.7.0

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  devtools_extensions: ^0.3.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true
