name: github_issue_app
description: "GitHub issue viewer app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true
